databases:
  - name: guildhall_db
    databaseName: guildhall_db
    user: gorebash
    plan: starter

services:
  - type: web
    name: guildhall
    runtime: ruby
    plan: starter
    buildCommand: "./bin/render-build.sh"
    preDeployCommand: "bundle exec rails db:migrate"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: guildhall_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
